import { readFile, rename, stat, writeFile } from 'node:fs/promises';
import path from 'node:path';
import type { ExecutionRecord, TokenUsage } from '../execution/execution-record.ts';
import { readArtifact, type ArtifactText, type IterationArtifacts, type SessionArtifacts, type SessionSummary } from '../session-history/session-history.ts';
import { JOURNAL_ENTRY_KINDS, isJournalEntryKind, type JournalEntryKind } from './journal-types.ts';

export { JOURNAL_ENTRY_KINDS, isJournalEntryKind, type JournalEntryKind };

/**
 * M4.2 Development Journal: human-readable Markdown generated by AI Bridge from the
 * session's *verified* artifacts — execution records (M4.1), the hash-checked Claude report,
 * Codex's raw response, the exact prompts. Nothing is summarized by a model and nothing is
 * inferred: sections are copied verbatim from the reports/reviews, labelled with their
 * source, and anything unavailable is written as UNKNOWN.
 *
 * Files (flat, next to the existing `NNN-…` artifacts of `.ai-bridge/sessions/<id>/`):
 *   NNN-claude-report.md   verified metadata + Claude's report (verbatim)
 *   NNN-review.md          Codex's narrative review (verbatim) + parsed decision + exact next prompt
 *   session.md             compact index (rounds table, artifacts, session ids, token usage)
 *   final-report.md        whole-session report, once the run reached a final status
 * Existing, reused as-is: NNN-claude-prompt.md (exact prompt), NNN-extracted-prompt.md
 * (exact next prompt), NNN-chatgpt-review.md (Codex's raw response).
 *
 * Generation is idempotent — each file is fully derived from what is on disk and only
 * rewritten when its content changes — so recovery/resume can never duplicate entries.
 */

const PER_ROUND: readonly JournalEntryKind[] = ['CLAUDE_PROMPT', 'CLAUDE_REPORT', 'CHATGPT_REVIEW', 'RAW_CODEX_RESPONSE', 'NEXT_PROMPT'];

export const FINAL_STATUSES: readonly string[] = ['DONE', 'NEED_HUMAN', 'ERROR', 'STOPPED', 'STOPPED_MAX_ITERATIONS'];

export function journalFileName(kind: JournalEntryKind, iteration: number | null): string | null {
  if (kind === 'SESSION_INDEX') return 'session.md';
  if (kind === 'FINAL_REPORT') return 'final-report.md';
  if (iteration === null || !Number.isInteger(iteration) || iteration < 1 || iteration > 999) return null;
  const n = String(iteration).padStart(3, '0');
  switch (kind) {
    case 'CLAUDE_REPORT':
      return `${n}-claude-report.md`;
    case 'CHATGPT_REVIEW':
      return `${n}-review.md`;
    case 'CLAUDE_PROMPT':
      return `${n}-claude-prompt.md`;
    case 'NEXT_PROMPT':
      return `${n}-extracted-prompt.md`;
    case 'RAW_CODEX_RESPONSE':
      return `${n}-chatgpt-review.md`;
  }
}

export type RoundState = 'COMPLETED' | 'RUNNING' | 'FAILED' | 'INTERRUPTED' | 'STOPPED' | 'INCOMPLETE';

export interface JournalRound {
  iteration: number;
  state: RoundState;
  /** CONTINUE / DONE / NEED_HUMAN as parsed from Codex's response; null = none/invalid. */
  verdict: string | null;
  available: JournalEntryKind[];
}

export interface JournalIndex {
  runId: string;
  status: string;
  maxIterations: number | null;
  rounds: JournalRound[];
  hasSessionIndex: boolean;
  hasFinalReport: boolean;
}

// ---------------------------------------------------------------------------
// Markdown helpers (pure)
// ---------------------------------------------------------------------------

/** Lines under `## <heading>` (case-insensitive, exact name) up to the next # / ## heading. */
export function extractSection(markdown: string, heading: string): string | null {
  const lines = markdown.replace(/\r\n/g, '\n').split('\n');
  const want = heading.trim().toLowerCase();
  let inFence = false;
  let start = -1;
  const out: string[] = [];
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    if (/^\s*(```|~~~)/.test(line)) inFence = !inFence;
    if (!inFence && /^#{1,2}\s/.test(line)) {
      if (start !== -1) break;
      const name = line.replace(/^#{1,2}\s+/, '').trim().toLowerCase();
      if (name === want || name.startsWith(`${want} (`)) start = i;
      continue;
    }
    if (start !== -1) out.push(line);
  }
  if (start === -1) return null;
  const text = out.join('\n').trim();
  return text === '' ? null : text;
}

/** A code fence longer than any backtick run inside `text`, so content can never escape it. */
export function fence(text: string, info = 'text'): string {
  const longest = Math.max(0, ...[...text.matchAll(/`+/g)].map((m) => m[0].length));
  const f = '`'.repeat(Math.max(3, longest + 1));
  return `${f}${info}\n${text.replace(/\n$/, '')}\n${f}`;
}

/** Codex's own narrative: the text outside the <AI_BRIDGE_RESPONSE> block. */
export function codexNarrative(raw: string): string | null {
  const open = raw.indexOf('<AI_BRIDGE_RESPONSE>');
  const close = raw.lastIndexOf('</AI_BRIDGE_RESPONSE>');
  if (open === -1) return null;
  const before = raw.slice(0, open).trim();
  const after = close === -1 ? '' : raw.slice(close + '</AI_BRIDGE_RESPONSE>'.length).trim();
  const text = [before, after].filter(Boolean).join('\n\n');
  return text === '' ? null : text;
}

const nnn = (n: number) => String(n).padStart(3, '0');
const orUnknown = (v: string | number | null | undefined) => (v === null || v === undefined || v === '' ? 'UNKNOWN' : String(v));

function formatDuration(ms: number | null): string {
  if (ms === null) return 'UNKNOWN';
  const s = Math.round(ms / 1000);
  return `${Math.floor(s / 60)}m ${String(s % 60).padStart(2, '0')}s (${ms} ms)`;
}

export function usageLine(u: TokenUsage | null | undefined): string {
  if (!u) return 'UNKNOWN (the CLI reported no usable token usage for this call)';
  const parts = [`input ${u.inputTokens}`, `output ${u.outputTokens}`];
  if (u.cacheCreationInputTokens !== null) parts.push(`cache creation ${u.cacheCreationInputTokens}`);
  if (u.cacheReadInputTokens !== null) parts.push(`cache read ${u.cacheReadInputTokens}`);
  if (u.cachedInputTokens !== null) parts.push(`cached input ${u.cachedInputTokens}`);
  if (u.reasoningTokens !== null) parts.push(`reasoning ${u.reasoningTokens}`);
  return `${parts.join(', ')} — total ${u.totalTokens} (${u.totalFormula}; reported by the CLI)`;
}

/** M5.10.1: "why did this call (not) ask for permission?" — from the execution record only. */
export function permissionLine(rec: ExecutionRecord | undefined): string {
  const p = rec?.permission;
  if (!p) return 'UNKNOWN (not recorded — execution recorded before M5.10.1)';
  return `${p.resolved} — ${p.reason}; CLI: ${p.cliArgs.join(' ')}`;
}

const EVIDENCE: Record<string, string> = {
  CONFIRMED_BY_CLI: 'confirmed by the CLI',
  REQUESTED_NOT_CONFIRMED: 'requested by AI Bridge, not confirmed by the CLI',
  UNKNOWN: 'UNKNOWN',
};

function sessionIdLine(rec: ExecutionRecord | undefined): string {
  if (!rec) return 'UNKNOWN (no execution record)';
  const id = rec.cliSessionId.reported ?? rec.cliSessionId.requested;
  let text = `${orUnknown(id)} (${EVIDENCE[rec.cliSessionId.evidence] ?? rec.cliSessionId.evidence})`;
  if (rec.mode === 'RESUME') text += ` — resume continuity ${rec.continuity.verdict}${rec.continuity.verdict === 'MISMATCH' ? ` (requested ${orUnknown(rec.continuity.expected)})` : ''}`;
  return text;
}

export function roundState(it: IterationArtifacts): RoundState {
  const c = it.claudeExecution?.effectiveStatus;
  const x = it.codexExecution?.effectiveStatus;
  if (c === 'RUNNING' || x === 'RUNNING') return 'RUNNING';
  if (c === 'FAILED' || c === 'TIMEOUT' || x === 'FAILED' || x === 'TIMEOUT') return 'FAILED';
  if (c === 'INTERRUPTED' || x === 'INTERRUPTED') return 'INTERRUPTED';
  if (c === 'STOPPED' || x === 'STOPPED') return 'STOPPED';
  if (it.codexVerdict !== null) return 'COMPLETED';
  return 'INCOMPLETE';
}

// ---------------------------------------------------------------------------
// Renderers (pure: artifacts in, Markdown out)
// ---------------------------------------------------------------------------

export function renderClaudeReport(runId: string, it: IterationArtifacts): string | null {
  const report = it.report;
  if (report.availability !== 'AVAILABLE') return null;
  const rec = it.claudeExecution?.record;
  const recorded = typeof it.integrity?.reportHash === 'string' ? it.integrity.reportHash : null;
  const hashNote = recorded === null ? 'no integrity record to compare' : recorded === report.sha256 ? 'matches the integrity record' : 'DOES NOT match the integrity record';
  return [
    '# Claude Execution Report',
    '',
    '> Generated by AI Bridge from the M4.1 execution record and the validated report. The section',
    "> \"Report (verbatim)\" is Claude's own report, byte-for-byte as validated; the metadata above it",
    '> comes from the execution record, not from Claude.',
    '',
    '## Session',
    '',
    `- AI Bridge Session: ${runId}`,
    `- Iteration: ${nnn(it.iteration)}`,
    `- Claude CLI Session: ${sessionIdLine(rec)}`,
    `- Status: ${it.claudeExecution ? it.claudeExecution.effectiveStatus : 'UNKNOWN (no execution record — session recorded before M4.1)'}`,
    `- Exit code: ${orUnknown(rec?.process.exitCode)}`,
    `- Started: ${orUnknown(rec?.process.startedAt)}`,
    `- Completed: ${orUnknown(rec?.process.endedAt)}`,
    `- Duration: ${formatDuration(rec?.process.durationMs ?? null)}`,
    `- Prompt: ${nnn(it.iteration)}-claude-prompt.md — SHA-256 ${orUnknown(rec?.input.sha256 ?? it.claudePrompt?.sha256)}, ${orUnknown(rec?.input.bytes ?? it.claudePrompt?.bytes)} bytes`,
    `- Report SHA-256: ${report.sha256} (${hashNote}; source: ${report.source === 'REPORT_FILE' ? 'report file' : 'recovered from the input sent to Codex'})`,
    `- Token usage: ${usageLine(rec?.usage)}`,
    `- Permission policy: ${permissionLine(rec)}`,
    '',
    '## Report (verbatim)',
    '',
    report.text.trim(),
    '',
  ].join('\n');
}

export function renderReview(runId: string, it: IterationArtifacts): string | null {
  const raw = it.codexResponse;
  if (!raw) return null;
  const c = it.claudeExecution?.record;
  const x = it.codexExecution?.record;
  const narrative = codexNarrative(raw.text);
  const next = it.extractedPrompt;
  let nextText = 'UNKNOWN (no next prompt persisted)';
  if (next) {
    const where = it.codexVerdict === 'CONTINUE' ? " — sent to Claude as the next round's prompt." : ' — not sent to Claude (the run ended with this decision).';
    nextText = `Exact prompt persisted as ${nnn(it.iteration)}-extracted-prompt.md (SHA-256 ${next.sha256}, ${next.bytes} bytes)${where}\n\n${fence(next.text)}`;
  }
  return [
    '# ChatGPT Review',
    '',
    `> Generated by AI Bridge from Codex's raw response (${nnn(it.iteration)}-chatgpt-review.md, kept unchanged).`,
    '> "Review" is Codex\'s own text, verbatim. "Decision" and "Next Prompt" come from AI Bridge\'s',
    '> response parser, which is authoritative for control flow.',
    '',
    '## Session',
    '',
    `- AI Bridge Session: ${runId}`,
    `- Iteration: ${nnn(it.iteration)}`,
    `- Claude CLI Session: ${sessionIdLine(c)}`,
    `- Codex Thread: ${sessionIdLine(x)}`,
    `- Review Status: ${it.codexVerdict ?? 'UNKNOWN (response could not be parsed)'}`,
    `- Codex token usage: ${usageLine(x?.usage)}`,
    `- Codex permission policy: ${permissionLine(x)}`,
    '',
    '## Report Reviewed',
    '',
    it.report.availability === 'AVAILABLE' ? `- ${nnn(it.iteration)}-claude-report.md — report SHA-256 ${it.report.sha256}` : '- UNKNOWN (report not available)',
    '',
    '## Review (Codex, verbatim)',
    '',
    narrative ?? '_Codex returned no narrative review for this round — only the structured response block._',
    '',
    '## Decision',
    '',
    it.codexVerdict ?? 'UNKNOWN',
    '',
    '## Next Prompt',
    '',
    nextText,
    '',
  ].join('\n');
}

function reportSection(it: IterationArtifacts, heading: string): string | null {
  return it.report.availability === 'AVAILABLE' ? extractSection(it.report.text, heading) : null;
}

function reviewSection(it: IterationArtifacts, heading: string): string | null {
  const narrative = it.codexResponse ? codexNarrative(it.codexResponse.text) : null;
  return narrative ? extractSection(narrative, heading) : null;
}

function maxIterationsOf(artifacts: SessionArtifacts): number | null {
  const started = [...artifacts.events].reverse().find((e) => e.event === 'RUN_STARTED' && typeof e.maxIterations === 'number');
  if (started && typeof started.maxIterations === 'number') return started.maxIterations;
  const fromState = artifacts.state?.maxIterations;
  return typeof fromState === 'number' ? fromState : null;
}

function distinctIds(artifacts: SessionArtifacts, agent: 'claude' | 'codex'): string[] {
  const byId = new Map<string, { rounds: number[]; evidence: Set<string>; mismatch: number[] }>();
  for (const it of artifacts.iterations) {
    const rec = (agent === 'claude' ? it.claudeExecution : it.codexExecution)?.record;
    if (!rec) continue;
    const id = rec.cliSessionId.reported ?? rec.cliSessionId.requested ?? 'UNKNOWN';
    const entry = byId.get(id) ?? { rounds: [], evidence: new Set<string>(), mismatch: [] };
    entry.rounds.push(it.iteration);
    entry.evidence.add(EVIDENCE[rec.cliSessionId.evidence] ?? rec.cliSessionId.evidence);
    if (rec.continuity.verdict === 'MISMATCH') entry.mismatch.push(it.iteration);
    byId.set(id, entry);
  }
  if (byId.size === 0) return ['UNKNOWN (no execution records)'];
  return [...byId.entries()].map(
    ([id, e]) => `${id} — rounds ${e.rounds.join(', ')} (${[...e.evidence].join('; ')})${e.mismatch.length ? ` — resume MISMATCH in round(s) ${e.mismatch.join(', ')}` : ''}`,
  );
}

export function renderSessionIndex(summary: SessionSummary, artifacts: SessionArtifacts, projectName: string, present: Set<string>): string {
  const task = artifacts.iterations[0]?.claudePrompt?.text ?? null;
  const max = maxIterationsOf(artifacts);
  const rows = artifacts.iterations.map((it) => {
    const c = it.claudeExecution;
    const x = it.codexExecution;
    const report = it.report.availability === 'AVAILABLE' ? it.report.verification : it.report.availability;
    return `| ${it.iteration} | ${c ? c.effectiveStatus : 'UNKNOWN'} | ${orUnknown(c?.record.process.exitCode)} | ${report} | ${x ? x.effectiveStatus : 'UNKNOWN'} | ${it.codexVerdict ?? '—'} |`;
  });
  const link = (file: string, label: string) => (present.has(file) ? `[${label}](${file})` : null);
  const artifactLines = artifacts.iterations.map((it) => {
    const n = nnn(it.iteration);
    const links = [
      link(`${n}-claude-prompt.md`, 'Claude prompt'),
      link(`${n}-claude-report.md`, 'Claude report'),
      link(`${n}-review.md`, 'ChatGPT review'),
      link(`${n}-chatgpt-review.md`, 'raw Codex response'),
      link(`${n}-extracted-prompt.md`, 'next prompt'),
    ].filter(Boolean);
    return `- Round ${n}: ${links.length ? links.join(' · ') : 'no artifacts'}`;
  });
  const tokenRows = artifacts.iterations.map(
    (it) => `| ${it.iteration} | ${orUnknown(it.claudeExecution?.record.usage?.totalTokens)} | ${orUnknown(it.codexExecution?.record.usage?.totalTokens)} |`,
  );
  return [
    '# AI Bridge Development Session',
    '',
    `> Index generated by AI Bridge from this session's artifacts (project: ${projectName}).`,
    '',
    '## Task',
    '',
    task === null ? 'UNKNOWN (first prompt not available)' : fence(task),
    '',
    '## Status',
    '',
    `- Status: ${summary.status}`,
    `- Rounds: ${artifacts.iterations.length}${max !== null ? ` of at most ${max} (the run stops earlier when the reviewer returns DONE)` : ' (maximum UNKNOWN — session recorded before M4.2)'}`,
    `- Started: ${orUnknown(summary.startedAt)}`,
    `- Ended: ${orUnknown(summary.endedAt)}`,
    '',
    '## Iterations',
    '',
    '| Round | Claude | Exit | Report | ChatGPT (Codex) | Decision |',
    '|------:|--------|-----:|--------|-----------------|----------|',
    ...rows,
    '',
    '## Artifacts',
    '',
    ...artifactLines,
    present.has('final-report.md') ? '- [Final report](final-report.md)' : '- Final report: not generated yet (the run has no final status)',
    '',
    '## Session IDs',
    '',
    `- AI Bridge: ${summary.runId}`,
    ...distinctIds(artifacts, 'claude').map((l) => `- Claude CLI: ${l}`),
    ...distinctIds(artifacts, 'codex').map((l) => `- Codex thread: ${l}`),
    '',
    '## Token Usage (as reported by the CLIs)',
    '',
    '| Round | Claude total | Codex total |',
    '|------:|-------------:|------------:|',
    ...tokenRows,
    '',
    'UNKNOWN means the CLI did not report usage for that call; nothing is estimated. This is per-call usage, not account quota.',
    '',
  ].join('\n');
}

function collect(artifacts: SessionArtifacts, pick: (it: IterationArtifacts) => string | null, emptyText: string): string {
  const parts = artifacts.iterations.map((it) => ({ n: it.iteration, text: pick(it) })).filter((p) => p.text !== null);
  if (parts.length === 0) return emptyText;
  return parts.map((p) => `### Round ${nnn(p.n)}\n\n${p.text}`).join('\n\n');
}

export function renderFinalReport(summary: SessionSummary, artifacts: SessionArtifacts, projectName: string): string {
  const its = artifacts.iterations;
  const last = its[its.length - 1];
  const max = maxIterationsOf(artifacts);
  const task = its[0]?.claudePrompt?.text ?? null;
  let outcome: string;
  if (summary.status === 'DONE') outcome = `The reviewer returned DONE in round ${last?.iteration ?? '?'}.`;
  else if (summary.status === 'STOPPED_MAX_ITERATIONS') outcome = `The run stopped because the maximum of ${max ?? 'UNKNOWN'} review rounds was reached without a DONE decision.`;
  else if (summary.status === 'NEED_HUMAN') outcome = `The reviewer returned NEED_HUMAN in round ${last?.iteration ?? '?'} — a human decision is required.`;
  else if (summary.status === 'STOPPED') outcome = 'The run was stopped by the user.';
  else outcome = `The run ended with status ${summary.status}${summary.errorCode ? ` (${summary.errorCode})` : ''}.`;

  const lastClaudeSummary = last ? (reportSection(last, 'SUMMARY') ?? reportSection(last, 'CHANGES')) : null;
  const lastReviewSummary = last ? (reviewSection(last, 'Summary') ?? (last.codexResponse ? codexNarrative(last.codexResponse.text) : null)) : null;

  const timeline = its.map((it) => {
    const claude = reportSection(it, 'SUMMARY') ?? reportSection(it, 'CHANGES') ?? '_No report available for this round._';
    const narrative = it.codexResponse ? codexNarrative(it.codexResponse.text) : null;
    const review = narrative ? (extractSection(narrative, 'Summary') ?? narrative) : '_No narrative review (only the structured decision)._';
    return [`## Iteration ${nnn(it.iteration)}`, '', '### Claude Summary', '', claude, '', '### ChatGPT Review', '', review, '', '### Result', '', it.codexVerdict ?? `UNKNOWN (${roundState(it)})`].join('\n');
  });

  const files = [
    ['FILES CREATED', 'Files Created'],
    ['FILES MODIFIED', 'Files Modified'],
    ['FILES DELETED', 'Files Deleted'],
  ]
    .map(([h, title]) => `## ${title}\n\n${collect(artifacts, (it) => reportSection(it, h), 'Not reported.')}`)
    .join('\n\n');
  const verdictChain = its.map((it) => `Round ${it.iteration} → ${it.codexVerdict ?? 'UNKNOWN'}`).join('\n');
  const mermaid =
    its.length > 0
      ? fence(['flowchart LR', ...its.map((it, i) => `  R${it.iteration}["Round ${it.iteration}: ${it.codexVerdict ?? 'UNKNOWN'}"]${i < its.length - 1 ? ` --> R${its[i + 1].iteration}` : ''}`)].join('\n'), 'mermaid')
      : '';

  let remaining = 'UNKNOWN';
  if (last) remaining = reportSection(last, 'REMAINING WORK') ?? (summary.status === 'DONE' ? 'None reported (the reviewer returned DONE).' : (reportSection(last, 'NEXT_RECOMMENDATION') ?? 'Not reported.'));

  return [
    '# Development Session Report',
    '',
    "> Generated by AI Bridge from this session's artifacts only — no model was asked to summarize and",
    '> nothing is inferred. Sections marked "as reported by Claude" / "as reviewed by Codex" are copied',
    '> verbatim from those sources and were not independently verified by AI Bridge.',
    '',
    '## Task',
    '',
    task === null ? 'UNKNOWN' : fence(task),
    '',
    '## Session',
    '',
    `- AI Bridge Session: ${summary.runId}`,
    `- Project: ${projectName}`,
    `- Started: ${orUnknown(summary.startedAt)}`,
    `- Completed: ${orUnknown(summary.endedAt)}`,
    `- Final Status: ${summary.status}`,
    `- Total Iterations: ${its.length}${max !== null ? ` (maximum ${max})` : ''}`,
    '',
    '# Executive Summary',
    '',
    outcome,
    '',
    '**Last Claude summary (as reported by Claude):**',
    '',
    lastClaudeSummary ?? '_Not available._',
    '',
    '**Last review (as reviewed by Codex):**',
    '',
    lastReviewSummary ?? '_Not available._',
    '',
    '# Development Timeline',
    '',
    ...timeline.flatMap((t) => [t, '']),
    '# Major Development Phases (as reviewed by Codex)',
    '',
    collect(artifacts, (it) => reviewSection(it, 'Development Phase'), 'None established in this session.'),
    '',
    '# Files Changed (as reported by Claude)',
    '',
    files,
    '',
    '# Tests (as reported by Claude)',
    '',
    collect(artifacts, (it) => reportSection(it, 'TESTS'), 'Not reported.'),
    '',
    '# Important Decisions (as reported by Claude)',
    '',
    collect(artifacts, (it) => reportSection(it, 'DECISIONS'), 'Not reported.'),
    '',
    '# Problems Encountered',
    '',
    collect(
      artifacts,
      (it) => {
        const issues = reportSection(it, 'ISSUES');
        const found = reviewSection(it, 'Problems Found');
        const parts = [issues ? `Claude (ISSUES):\n\n${issues}` : null, found ? `Codex (Problems Found):\n\n${found}` : null].filter(Boolean);
        return parts.length ? parts.join('\n\n') : null;
      },
      'None reported.',
    ),
    '',
    '# Problems Resolved',
    '',
    'UNKNOWN — AI Bridge does not infer which problems were resolved. Compare "Problems Encountered" across rounds.',
    '',
    '# Remaining Work',
    '',
    remaining,
    '',
    '# Known Risks',
    '',
    last ? (reportSection(last, 'ISSUES') ?? 'None reported.') : 'UNKNOWN',
    '',
    '# Architecture Summary',
    '',
    'Not generated — AI Bridge does not infer architecture from a session. Decisions reported during the session are listed under "Important Decisions".',
    '',
    '# Interaction Timeline',
    '',
    fence(verdictChain),
    '',
    mermaid,
    '',
    '# Final Result',
    '',
    `${summary.status} after ${its.length} round(s). ${outcome}`,
    '',
  ].join('\n');
}

// ---------------------------------------------------------------------------
// Filesystem
// ---------------------------------------------------------------------------

/** Rewrites only on change, via temp file + rename so a concurrent reader never sees a torn file. */
async function writeIfChanged(file: string, content: string): Promise<void> {
  const existing = await readFile(file, 'utf8').catch(() => null);
  if (existing === content) return;
  const tmp = `${file}.${process.pid}.tmp`;
  await writeFile(tmp, content, 'utf8');
  await rename(tmp, file);
}

async function exists(file: string): Promise<boolean> {
  return stat(file).then(
    (s) => s.isFile(),
    () => false,
  );
}

/** (Re)generates every journal file for one session from its artifacts. Idempotent. */
export async function buildJournal(sessionDir: string, summary: SessionSummary, artifacts: SessionArtifacts, projectName: string): Promise<void> {
  for (const it of artifacts.iterations) {
    const report = renderClaudeReport(artifacts.runId, it);
    if (report !== null) await writeIfChanged(path.join(sessionDir, `${nnn(it.iteration)}-claude-report.md`), report);
    const review = renderReview(artifacts.runId, it);
    if (review !== null) await writeIfChanged(path.join(sessionDir, `${nnn(it.iteration)}-review.md`), review);
  }
  if (FINAL_STATUSES.includes(summary.status)) await writeIfChanged(path.join(sessionDir, 'final-report.md'), renderFinalReport(summary, artifacts, projectName));
  const present = new Set<string>();
  for (const it of artifacts.iterations) {
    for (const kind of PER_ROUND) {
      const name = journalFileName(kind, it.iteration);
      if (name && (await exists(path.join(sessionDir, name)))) present.add(name);
    }
  }
  if (await exists(path.join(sessionDir, 'final-report.md'))) present.add('final-report.md');
  await writeIfChanged(path.join(sessionDir, 'session.md'), renderSessionIndex(summary, artifacts, projectName, present));
}

export async function readJournalIndex(sessionDir: string, summary: SessionSummary, artifacts: SessionArtifacts): Promise<JournalIndex> {
  const rounds: JournalRound[] = [];
  for (const it of artifacts.iterations) {
    const available: JournalEntryKind[] = [];
    for (const kind of PER_ROUND) {
      const name = journalFileName(kind, it.iteration);
      if (name && (await exists(path.join(sessionDir, name)))) available.push(kind);
    }
    rounds.push({ iteration: it.iteration, state: roundState(it), verdict: it.codexVerdict, available });
  }
  return {
    runId: artifacts.runId,
    status: summary.status,
    maxIterations: maxIterationsOf(artifacts),
    rounds,
    hasSessionIndex: await exists(path.join(sessionDir, 'session.md')),
    hasFinalReport: await exists(path.join(sessionDir, 'final-report.md')),
  };
}

export type JournalEntry = ArtifactText & { kind: JournalEntryKind; iteration: number | null };

/** One journal entry by fixed file name (never a caller-supplied path), capped by readArtifact. */
export async function readJournalEntry(sessionDir: string, kind: JournalEntryKind, iteration: number | null): Promise<JournalEntry | null> {
  const name = journalFileName(kind, iteration);
  if (!name) return null;
  const artifact = await readArtifact(path.join(sessionDir, name));
  if (!artifact) return null;
  return { ...artifact, path: name, kind, iteration };
}
